"""Enrich SOS requests with altitude battery and category

Revision ID: 0681448f4ef9
Revises: a4d01742343e
Create Date: 2026-04-03 08:49:30.753092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0681448f4ef9'
down_revision: Union[str, None] = 'a4d01742343e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sos_requests', sa.Column('altitude', sa.Float(), nullable=True))
    op.add_column('sos_requests', sa.Column('battery_level', sa.Float(), nullable=True))
    
    # Add category as nullable first to handle existing data
    op.add_column('sos_requests', sa.Column('category', sa.String(length=20), nullable=True))
    op.execute("UPDATE sos_requests SET category = 'GENERAL'")
    op.alter_column('sos_requests', 'category', nullable=False)
    
    op.add_column('sos_requests', sa.Column('responder_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sos_requests', 'responder_name')
    op.drop_column('sos_requests', 'category')
    op.drop_column('sos_requests', 'battery_level')
    op.drop_column('sos_requests', 'altitude')
    # ### end Alembic commands ###
