"""initial_schema

Revision ID: 3cc10b768275
Revises: 
Create Date: 2026-03-30 17:32:26.433933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cc10b768275'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cameras',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('camera_id', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('location_label', sa.String(length=200), nullable=True),
        sa.Column('source', sa.String(length=500), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('low_thresh', sa.Integer(), server_default='30', nullable=False),
        sa.Column('high_thresh', sa.Integer(), server_default='75', nullable=False),
        sa.Column('max_age', sa.Integer(), server_default='10', nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras')),
        sa.UniqueConstraint('camera_id', name=op.f('uq_cameras_camera_id'))
    )
    op.create_table(
        'sos_requests',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('device_id', sa.String(length=200), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_sos_requests'))
    )
    op.create_table(
        'alerts',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('camera_id', sa.String(length=50), nullable=False),
        sa.Column('severity', sa.String(length=10), nullable=False),
        sa.Column('person_count', sa.Integer(), nullable=True),
        sa.Column('threshold', sa.Integer(), nullable=True),
        sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_camera_id'), 'alerts', ['camera_id'], unique=False)
    op.create_table(
        'crowd_events',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('camera_id', sa.String(length=50), nullable=False),
        sa.Column('person_count', sa.Integer(), nullable=False),
        sa.Column('density_level', sa.String(length=10), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_crowd_events'))
    )
    op.create_index(op.f('ix_crowd_events_camera_id'), 'crowd_events', ['camera_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crowd_events_camera_id'), table_name='crowd_events')
    op.drop_table('crowd_events')
    op.drop_index(op.f('ix_alerts_camera_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('sos_requests')
    op.drop_table('cameras')
    # ### end Alembic commands ###
