"""Add alert messages and recommendations

Revision ID: 4d1e5adc965b
Revises: afda54f16e85
Create Date: 2026-04-29 21:40:56.336936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d1e5adc965b'
down_revision: Union[str, None] = 'afda54f16e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('push_token', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('device_id', name=op.f('pk_users'))
    )
    op.add_column('alerts', sa.Column('message', sa.String(length=500), nullable=True))
    op.add_column('alerts', sa.Column('recommendation', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'recommendation')
    op.drop_column('alerts', 'message')
    op.drop_table('users')
    # ### end Alembic commands ###
