"""add_panic_metrics_and_indices

Revision ID: 6ed5d886b0c9
Revises: 0681448f4ef9
Create Date: 2026-04-03 17:45:41.103818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed5d886b0c9'
down_revision: Union[str, None] = '0681448f4ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crowd_events', sa.Column('panic_score', sa.Integer(), nullable=True))
    op.add_column('crowd_events', sa.Column('is_panic', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_crowd_events_timestamp'), 'crowd_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crowd_events_timestamp'), table_name='crowd_events')
    op.drop_column('crowd_events', 'is_panic')
    op.drop_column('crowd_events', 'panic_score')
    # ### end Alembic commands ###
