"""fix_crowd_event_column_types

Revision ID: afda54f16e85
Revises: 6ed5d886b0c9
Create Date: 2026-04-03 18:16:28.822303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afda54f16e85'
down_revision: Union[str, None] = '6ed5d886b0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crowd_events', 'panic_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='panic_score::float')
    op.alter_column('crowd_events', 'is_panic',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='is_panic::boolean')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crowd_events', 'is_panic',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('crowd_events', 'panic_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
